FROM golang:1.21 AS build
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o evntboard-api ./cmd/api

FROM alpine:latest AS api
COPY --from=build /app/evntboard-api .
EXPOSE 8080
CMD ["./evntboard-api", "serve", "--http=0.0.0.0:8080"]