FROM golang:1.21 AS build
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o evntboard-module ./cmd/module

FROM alpine:latest AS module
COPY --from=build /app/evntboard-module .
EXPOSE 8080
CMD ["./evntboard-module"]