FROM golang:1.21 AS build
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o evntboard-event ./cmd/event

FROM alpine:latest AS event
COPY --from=build /app/evntboard-event .
EXPOSE 8080
CMD ["./evntboard-event"]